# Generated by Django 4.1 on 2022-09-13 13:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='network/profile_pictures/default.jpeg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='profile_image'),
        ),
    ]
