# Generated by Django 4.1 on 2022-09-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_following_followers_alter_following_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
