# Generated by Django 4.1 on 2022-09-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_people_liking_the_post_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='people_liking_the_post',
        ),
        migrations.AlterField(
            model_name='following',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='all_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='all_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_liking_the_post', models.ManyToManyField(blank=True, related_name='people_liking', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='network.post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
