# Generated by Django 4.1 on 2022-09-15 21:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='network/static/profile_pictures/default.jpeg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='network/static/profile_pictures'),
        ),
    ]
