# Generated by Django 4.1 on 2022-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
