# Generated by Django 4.1 on 2022-09-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_likes',
        ),
    ]
