# Generated by Django 4.1 on 2022-09-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commented_date',
            new_name='date',
        ),
    ]
