# Generated by Django 4.1 on 2022-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bids',
        ),
        migrations.AddField(
            model_name='listings',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing_bids', to='auctions.bids'),
        ),
    ]
